#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 19 11:04:54 2021

@author: josephmontenegro
"""
#When we return multiole values in a function - we usally have tuples
PI = 3.14159

def circleInfo(radious, color):
  diameter = 2 * radious
  circumference = 2 * radious * PI
  area = PI * radious**2
  color = color
  return (diameter, circumference, area, color)
  

c1 = circleInfo(3, "red")
print(c1)
  
c2 = circleInfo(6, "blue")
c2_d, c2_c, c2_a, c2_col = c2
print("Circle 2's area: ", c2_a)
  
letter_tuple = ('g', 'a', 'b', 'l', 'e', 's')
print(letter_tuple[2:])
print(letter_tuple[-2])

#cannont change elements of a tuple
#Error: letter_tuple[0]= 'G'
#To make a change - need to cover to list and back
letter_list = list(letter_tuple)
letter_list[0] = 'G'
letter_tuple = tuple(letter_list)
print(letter_tuple)

#To create a tuple:use parentheses parentheses 
word_tuple = ("One Element",)
print(type(word_tuple))

words_tuple = ("New York", "New Jersey", "Jersey", "Jersey", "Jersey", "Binghampton", "Miami")
for location in words_tuple:
  print(location, end = " ")
  print(words_tuple.count(location))
